### ISSUE TITLE
请问autostreaming找不到如何解决

### ISSUE THREAD

**Issue by LOVECHEN** [ossrs/srs-unity#1]
An error occurred while resolving packages:
  Project has invalid dependencies:
    com.unity.modules.autostreaming: Package [com.unity.modules.autostreaming@1.0.0] cannot be found

A re-import of the project may be required to fix the issue or a manual modification of /Users/love/Downloads/srs-unity-main/Packages/manifest.json file.

包管理器里提示

This package is not available offline.

请问需要如何操作？

**Comment by winlinvip** [comment]
Please upgrade your Unity IDE.
