### ISSUE TITLE
Since it's in English, please choose the international version of Unity...

### ISSUE THREAD

**Issue by kane9527-e** [ossrs/srs-unity#11]
The international version has a larger audience

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
What is the difference between the international version and the domestic version? The code and engineering should be compatible, right? Can't the international version use the current examples and code?

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
Fixed by https://github.com/ossrs/srs-unity/commit/c6a9d7c3fa384762b8ee84f9bf8f262bbdfa00bc
