### ISSUE TITLE
RTC streaming only has audio, no video

### ISSUE THREAD

**Issue by kane9527-e** [ossrs/srs-unity#12]
server 5.0,  and com.unity.webrtc 3.0.0-pre.4 config: rtmp2rtc.conf
![image](https://github.com/ossrs/srs-unity/assets/9569527/0900ed70-34ae-4735-a067-8d6bba4043c5)
![image](https://github.com/ossrs/srs-unity/assets/9569527/4acb772e-073c-4d11-b4d4-6d0ba7cea377)

![image](https://github.com/ossrs/srs-unity/assets/9569527/c1822a69-3d18-434b-b5d5-a746d8a0f9f5)
![image](https://github.com/ossrs/srs-unity/assets/9569527/2fcd15a9-45e8-4087-b1b9-595a73af0575)

`TRANS_BY_GPT4`

**Comment by kane9527-e** [comment]
I hope you can reply

**Comment by kane9527-e** [comment]
Do you plan to maintain this example？

**Comment by kane9527-e** [comment]
Request for reply

`TRANS_BY_GPT4`

**Comment by kane9527-e** [comment]
Save life

`TRANS_BY_GPT4`

**Comment by winlinvip** [comment]
Dup to #5, please don't file duplicated issues.

Fixed in [3.0.0-pre.5](https://github.com/Unity-Technologies/com.unity.webrtc/milestone/24), see https://github.com/Unity-Technologies/com.unity.webrtc/issues/882
