### ISSUE TITLE
There is an echo during the call

### ISSUE THREAD

**Issue by stay-cnsj** [ossrs/srs-unity#3]
I want to build a conferencing software, but there is an echo during the call. It may be that the echo cancellation is not done. Is there any solution?

**Comment by winlinvip** [comment]
Any updates?

**Comment by stay-cnsj** [comment]
After debugging, I found that the root cause of the noise is that unity-webrtc does not implement echo cancellation. I checked and the official said that this function will be implemented in the future. https://github.com/Unity-Technologies/UnityRenderStreaming/issues/563
Solving this problem is difficult for us. Does this mean that we need to wait for the official implementation of unity-webrtc?

**Comment by winlinvip** [comment]
Yep, we can do nothing but wait. So I would close this issue.

Seems will support in next version, see https://github.com/Unity-Technologies/com.unity.webrtc/issues/587#issuecomment-1374792618
